### ISSUE TITLE
The characters in the picture are misspelled

### ISSUE THREAD

**Issue by ghost** [phoe/the-elusive-language#1]
very nice photo
but the "open source" in  traditional Chinese is 開源 not 開滿 at mkcl.png

**Comment by phoe** [comment]
To the best of my knowledge, 満開 in Japanese is read as ["mankai"](https://www.tanoshiijapanese.com/dictionary/entry_comments.cfm?entry_id=50847), which is the first part of the name of "ManKai Common Lisp", and this is where the two kanji come from.

Does this sound right? I have no idea what kind of interaction there might be between Chinese and Japanese readings of this form.

(It's also a surprise to me that this is so close to "open source" if we reverse the order of the two symbols!)

**Comment by ghost** [comment]
Thanks for the reply, you are right.
Please forgive me for asking this question rashly without knowing mkcl, sorry.
